package hostmock.corba;


/**
* hostmock/corba/HostOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Host.idl
* Wednesday, October 11, 2017 4:06:32 PM UTC
*/

public interface HostOperations 
{
  void sndAndRcv (String inq, org.omg.CORBA.StringHolder ans);
} // interface HostOperations
