package hostmock.corba;


/**
* hostmock/corba/Host.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Host.idl
* Sunday, October 15, 2017 2:21:43 PM UTC
*/

public interface Host extends HostOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Host
