package hostmock.corba;


/**
* hostmock/corba/HostOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Host.idl
* Monday, October 9, 2017 1:38:56 PM UTC
*/

public interface HostOperations 
{
  void sndAndRcv (String inq, org.omg.CORBA.StringHolder ans);
} // interface HostOperations
