package hostmock.corba;


/**
* hostmock/corba/HostOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Host.idl
* Thursday, October 12, 2017 11:36:21 PM UTC
*/

public interface HostOperations 
{
  void sndAndRcv (String inq, org.omg.CORBA.StringHolder ans);
} // interface HostOperations
