package poa;


/**
* poa/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Hello.idl
* Sunday, December 10, 2017 12:22:07 PM UTC
*/

public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
