package poa;


/**
* poa/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Hello.idl
* Saturday, October 7, 2017 3:19:04 PM UTC
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
