package poa;


/**
* poa/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Hello.idl
* Sunday, October 15, 2017 2:21:43 PM UTC
*/

public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
