package rmi;

/**
* rmi/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Hello.idl
* Saturday, October 7, 2017 5:22:19 AM UTC
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public rmi.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (rmi.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = rmi.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    rmi.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return rmi.HelloHelper.type ();
  }

}
