package rmi;


/**
* rmi/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Hello.idl
* Saturday, October 7, 2017 5:22:19 AM UTC
*/

public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
