package rmi;


/**
* rmi/HelloPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl/Hello.idl
* Saturday, October 7, 2017 5:22:19 AM UTC
*/

public class HelloPOATie extends HelloPOA
{

  // Constructors

  public HelloPOATie ( rmi.HelloOperations delegate ) {
      this._impl = delegate;
  }
  public HelloPOATie ( rmi.HelloOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public rmi.HelloOperations _delegate() {
      return this._impl;
  }
  public void _delegate (rmi.HelloOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String sayHello ()
  {
    return _impl.sayHello();
  } // sayHello

  public void shutdown ()
  {
    _impl.shutdown();
  } // shutdown

  private rmi.HelloOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class HelloPOATie
